/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
/* Header for class com_demon_glass_TestJni */

#ifndef TestJni
#define TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demon_glass_TestJni
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demon_jni_TestJni_hello
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
